apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ezdocstoragemrk3 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ezdocstoragemrk3 
    spec:
      containers:
        - name: ezdocstoragemrk3 
          image: capstonecr.azurecr.io/ezdocstoragemrk3
          ports:
          - containerPort: 80